USE viet_construction_cms;

DELETE FROM Posts
WHERE Slug IN (
    'cap-nhat-tien-do-goi-thau-ha-tang-kcn-song-han',
    'viet-thanh-cong-mo-rong-doi-ngu-chi-huy-cong-truong',
    'nghiem-thu-giai-doan-ket-cau-du-an-nha-xuong-binh-duong',
    'chuoi-hoat-dong-an-toan-lao-dong-quy-i-2026',
    'thong-tin-hop-tac-voi-doi-tac-co-dien-mien-trung',
    'bao-cao-cap-nhat-du-an-kho-lanh-long-an',
    'viet-thanh-cong-hoan-thanh-ban-giao-giai-doan-1',
    'hoi-thao-noi-bo-ve-quan-tri-tien-do-thi-cong',
    'thong-bao-lich-nghi-le-30-4-va-1-5',
    'thong-bao-tiep-nhan-ho-so-thau-phu-co-khi',
    'thong-bao-cap-nhat-quy-trinh-an-toan-hien-truong',
    'thong-bao-moi-hop-dao-tao-can-bo-ky-thuat',
    'thong-bao-dieu-chinh-ke-hoach-nghiem-thu-noi-bo',
    'thong-bao-bo-sung-ho-so-nang-luc-nha-cung-cap',
    'thong-bao-ke-hoach-bao-tri-he-thong-website-cms'
);

INSERT INTO Posts (
    Title,
    Slug,
    Summary,
    BodyHtml,
    MetaDescription,
    FeaturedImageUrl,
    PostType,
    CategoryId,
    IsFeatured,
    IsPublished,
    PublishedAtUtc,
    JobLocation,
    ExperienceRequirement,
    SalaryRange,
    ApplicationDeadline,
    CreatedAtUtc,
    UpdatedAtUtc
) VALUES
(
    'Cập nhật tiến độ gói thầu hạ tầng KCN Sông Hàn',
    'cap-nhat-tien-do-goi-thau-ha-tang-kcn-song-han',
    'Ban điều hành dự án cập nhật mốc thi công hạ tầng kỹ thuật, hệ thống thoát nước và nền đường nội bộ tại KCN Sông Hàn.',
    '<p>Ban điều hành dự án đã hoàn thành các hạng mục san nền, hệ thống thoát nước mưa và phần lớn tuyến giao thông nội bộ.</p><p>Các tổ đội đang tập trung nguồn lực cho giai đoạn hoàn thiện hạ tầng kỹ thuật để bảo đảm mốc bàn giao theo hợp đồng.</p>',
    'Cập nhật tiến độ gói thầu hạ tầng KCN Sông Hàn do Việt Thành Công triển khai.',
    '/images/project-bridge.svg',
    'News',
    1,
    1,
    1,
    '2026-03-24 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-24 02:00:00',
    '2026-03-24 02:00:00'
),
(
    'Việt Thành Công mở rộng đội ngũ chỉ huy công trường',
    'viet-thanh-cong-mo-rong-doi-ngu-chi-huy-cong-truong',
    'Do nhu cầu triển khai đồng thời nhiều dự án công nghiệp và dân dụng, doanh nghiệp tiếp tục kiện toàn bộ máy chỉ huy công trường tại miền Trung và miền Nam.',
    '<p>Khối điều hành dự án đã hoàn tất kế hoạch bổ sung nhân sự chỉ huy công trường, QA/QC và điều phối vật tư.</p><p>Việc mở rộng bộ máy giúp tăng khả năng kiểm soát tiến độ, an toàn và chất lượng trên từng hạng mục.</p>',
    'Việt Thành Công mở rộng đội ngũ chỉ huy công trường nhằm đáp ứng nhu cầu triển khai dự án mới.',
    '/images/project-office.svg',
    'News',
    1,
    1,
    1,
    '2026-03-22 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-22 02:00:00',
    '2026-03-22 02:00:00'
),
(
    'Nghiệm thu giai đoạn kết cấu dự án nhà xưởng Bình Dương',
    'nghiem-thu-giai-doan-ket-cau-du-an-nha-xuong-binh-duong',
    'Giai đoạn kết cấu chính của dự án nhà xưởng tại Bình Dương đã được nghiệm thu nội bộ, sẵn sàng chuyển sang phần hoàn thiện.',
    '<p>Đội ngũ kỹ thuật đã hoàn thành kiểm tra chất lượng toàn bộ hạng mục kết cấu chính và hồ sơ nghiệm thu nội bộ.</p><p>Dự án tiếp tục bước sang giai đoạn hoàn thiện kiến trúc và lắp đặt cơ điện theo tiến độ cập nhật.</p>',
    'Nghiệm thu giai đoạn kết cấu dự án nhà xưởng Bình Dương.',
    '/images/project-residential.svg',
    'News',
    1,
    0,
    1,
    '2026-03-20 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-20 02:00:00',
    '2026-03-20 02:00:00'
),
(
    'Chuỗi hoạt động an toàn lao động quý I/2026',
    'chuoi-hoat-dong-an-toan-lao-dong-quy-i-2026',
    'Doanh nghiệp triển khai chương trình kiểm tra hiện trường, đào tạo nhanh và đánh giá tuân thủ an toàn tại các công trình trọng điểm.',
    '<p>Trong quý I/2026, công ty tổ chức kiểm tra an toàn định kỳ tại các công trường và các buổi huấn luyện ngắn cho tổ đội thi công.</p><p>Các biên bản khắc phục được cập nhật tập trung để theo dõi đến khi hoàn tất.</p>',
    'Chuỗi hoạt động an toàn lao động quý I/2026 của Việt Thành Công.',
    '/images/project-office.svg',
    'News',
    1,
    0,
    1,
    '2026-03-18 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-18 02:00:00',
    '2026-03-18 02:00:00'
),
(
    'Thông tin hợp tác với đối tác cơ điện miền Trung',
    'thong-tin-hop-tac-voi-doi-tac-co-dien-mien-trung',
    'Việt Thành Công và đối tác cơ điện khu vực miền Trung thống nhất kế hoạch phối hợp nguồn lực cho các dự án nhà xưởng và thương mại.',
    '<p>Hai bên đã thống nhất nguyên tắc phối hợp ở các gói cơ điện có yêu cầu triển khai nhanh và kiểm soát hồ sơ chặt chẽ.</p><p>Việc hợp tác giúp nâng cao khả năng đáp ứng cho các dự án công nghiệp quy mô lớn.</p>',
    'Thông tin hợp tác giữa Việt Thành Công và đối tác cơ điện miền Trung.',
    '/images/project-bridge.svg',
    'News',
    1,
    0,
    1,
    '2026-03-16 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-16 02:00:00',
    '2026-03-16 02:00:00'
),
(
    'Báo cáo cập nhật dự án kho lạnh Long An',
    'bao-cao-cap-nhat-du-an-kho-lanh-long-an',
    'Khối dự án phát hành báo cáo cập nhật tháng về hạng mục nền, móng và hệ thống khung thép tại công trình kho lạnh Long An.',
    '<p>Các hạng mục nền, móng và kết cấu thép của dự án kho lạnh Long An đang được triển khai đúng kế hoạch đã phê duyệt.</p><p>Đội ngũ điều hành tiếp tục phối hợp chặt với nhà cung cấp vật tư để bảo đảm tiến độ lắp dựng.</p>',
    'Báo cáo cập nhật dự án kho lạnh Long An do Việt Thành Công triển khai.',
    '/images/project-residential.svg',
    'News',
    1,
    0,
    1,
    '2026-03-14 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-14 02:00:00',
    '2026-03-14 02:00:00'
),
(
    'Việt Thành Công hoàn thành bàn giao giai đoạn 1',
    'viet-thanh-cong-hoan-thanh-ban-giao-giai-doan-1',
    'Một dự án công nghiệp tại miền Trung đã hoàn tất bàn giao giai đoạn 1, đáp ứng các yêu cầu về tiến độ, chất lượng và hồ sơ nghiệm thu.',
    '<p>Hạng mục bàn giao giai đoạn 1 đã hoàn thiện đầy đủ hồ sơ chất lượng, biên bản nghiệm thu và khối lượng theo xác nhận của các bên liên quan.</p><p>Đây là cơ sở để doanh nghiệp tiếp tục triển khai giai đoạn tiếp theo với tiến độ ổn định.</p>',
    'Việt Thành Công hoàn thành bàn giao giai đoạn 1 của một dự án công nghiệp tại miền Trung.',
    '/images/project-office.svg',
    'News',
    1,
    1,
    1,
    '2026-03-12 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-12 02:00:00',
    '2026-03-12 02:00:00'
),
(
    'Hội thảo nội bộ về quản trị tiến độ thi công',
    'hoi-thao-noi-bo-ve-quan-tri-tien-do-thi-cong',
    'Khối vận hành tổ chức hội thảo nội bộ nhằm chuẩn hóa cách theo dõi tiến độ, hồ sơ hiện trường và cơ chế cảnh báo rủi ro chậm tiến độ.',
    '<p>Hội thảo tập trung vào các biểu mẫu điều hành, báo cáo ngày và phương pháp phối hợp giữa chỉ huy trưởng, kỹ thuật và vật tư.</p><p>Nội dung được xây dựng để áp dụng thống nhất tại các công trình trọng điểm trong năm 2026.</p>',
    'Hội thảo nội bộ về quản trị tiến độ thi công tại Việt Thành Công.',
    '/images/project-bridge.svg',
    'News',
    1,
    0,
    1,
    '2026-03-10 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-10 02:00:00',
    '2026-03-10 02:00:00'
),
(
    'Thông báo lịch nghỉ lễ 30/4 và 1/5',
    'thong-bao-lich-nghi-le-30-4-va-1-5',
    'Doanh nghiệp thông báo lịch nghỉ lễ 30/4 và 1/5 đối với khối văn phòng và phương án trực điều hành tại công trường.',
    '<p>Khối văn phòng nghỉ lễ theo lịch chung của công ty, trong khi các dự án vẫn bố trí nhân sự trực để duy trì điều phối và bảo đảm an toàn hiện trường.</p><p>Các đầu mối liên hệ khẩn cấp được cập nhật đến từng ban điều hành dự án.</p>',
    'Thông báo lịch nghỉ lễ 30/4 và 1/5 của Việt Thành Công.',
    '/images/project-office.svg',
    'Announcement',
    2,
    0,
    1,
    '2026-03-09 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-09 02:00:00',
    '2026-03-09 02:00:00'
),
(
    'Thông báo tiếp nhận hồ sơ thầu phụ cơ khí',
    'thong-bao-tiep-nhan-ho-so-thau-phu-co-khi',
    'Phòng đấu thầu thông báo tiếp nhận hồ sơ năng lực từ các đơn vị thầu phụ cơ khí phục vụ các dự án công nghiệp năm 2026.',
    '<p>Các đơn vị quan tâm vui lòng gửi hồ sơ năng lực, danh sách thiết bị và các dự án đã thực hiện về phòng đấu thầu theo thời gian thông báo.</p><p>Doanh nghiệp ưu tiên các đơn vị có kinh nghiệm triển khai nhà xưởng và công trình công nghiệp.</p>',
    'Thông báo tiếp nhận hồ sơ thầu phụ cơ khí cho các dự án công nghiệp năm 2026.',
    '/images/project-bridge.svg',
    'Announcement',
    2,
    0,
    1,
    '2026-03-07 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-07 02:00:00',
    '2026-03-07 02:00:00'
),
(
    'Thông báo cập nhật quy trình an toàn hiện trường',
    'thong-bao-cap-nhat-quy-trinh-an-toan-hien-truong',
    'Ban an toàn phát hành phiên bản cập nhật của quy trình kiểm tra hiện trường, quản lý giấy phép làm việc và kiểm soát thiết bị thi công.',
    '<p>Phiên bản cập nhật bổ sung yêu cầu kiểm tra chéo trước các công tác có rủi ro cao và thống nhất biểu mẫu ghi nhận hiện trường.</p><p>Các dự án có trách nhiệm triển khai phổ biến ngay cho đội ngũ kỹ thuật và thầu phụ liên quan.</p>',
    'Thông báo cập nhật quy trình an toàn hiện trường áp dụng tại các dự án của Việt Thành Công.',
    '/images/project-residential.svg',
    'Announcement',
    2,
    0,
    1,
    '2026-03-05 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-05 02:00:00',
    '2026-03-05 02:00:00'
),
(
    'Thông báo mời họp đào tạo cán bộ kỹ thuật',
    'thong-bao-moi-hop-dao-tao-can-bo-ky-thuat',
    'Khối kỹ thuật tổ chức buổi đào tạo nội bộ về hồ sơ nghiệm thu, quản lý bản vẽ và phối hợp shopdrawing tại các dự án mới.',
    '<p>Buổi đào tạo dành cho chỉ huy trưởng, kỹ sư hiện trường, QA/QC và nhân sự triển khai hồ sơ.</p><p>Nội dung tập trung vào chuẩn hóa biểu mẫu, kiểm soát khối lượng và phối hợp liên phòng ban.</p>',
    'Thông báo mời họp đào tạo cán bộ kỹ thuật của Việt Thành Công.',
    '/images/project-office.svg',
    'Announcement',
    2,
    0,
    1,
    '2026-03-03 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-03 02:00:00',
    '2026-03-03 02:00:00'
),
(
    'Thông báo điều chỉnh kế hoạch nghiệm thu nội bộ',
    'thong-bao-dieu-chinh-ke-hoach-nghiem-thu-noi-bo',
    'Phòng vận hành điều chỉnh lịch nghiệm thu nội bộ cho một số hạng mục để đồng bộ với tiến độ cung ứng vật tư và điều kiện thi công thực tế.',
    '<p>Lịch nghiệm thu điều chỉnh đã được cập nhật đến các ban điều hành dự án và các bộ phận liên quan.</p><p>Doanh nghiệp yêu cầu tiếp tục duy trì đầy đủ hồ sơ hiện trường và biên bản kiểm tra theo quy định nội bộ.</p>',
    'Thông báo điều chỉnh kế hoạch nghiệm thu nội bộ tại các dự án của Việt Thành Công.',
    '/images/project-bridge.svg',
    'Announcement',
    2,
    0,
    1,
    '2026-03-01 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-03-01 02:00:00',
    '2026-03-01 02:00:00'
),
(
    'Thông báo bổ sung hồ sơ năng lực nhà cung cấp',
    'thong-bao-bo-sung-ho-so-nang-luc-nha-cung-cap',
    'Phòng mua sắm đề nghị các nhà cung cấp trong danh sách hợp tác cập nhật lại hồ sơ pháp lý, catalogue và năng lực cung ứng mới nhất.',
    '<p>Việc cập nhật hồ sơ giúp bộ phận mua sắm và đấu thầu chuẩn hóa dữ liệu đối tác cho chuỗi dự án năm 2026.</p><p>Nhà cung cấp vui lòng gửi bản mềm về đầu mối tiếp nhận trước thời hạn thông báo.</p>',
    'Thông báo bổ sung hồ sơ năng lực nhà cung cấp phục vụ công tác mua sắm và đấu thầu.',
    '/images/project-residential.svg',
    'Announcement',
    2,
    0,
    1,
    '2026-02-27 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-02-27 02:00:00',
    '2026-02-27 02:00:00'
),
(
    'Thông báo kế hoạch bảo trì hệ thống website CMS',
    'thong-bao-ke-hoach-bao-tri-he-thong-website-cms',
    'Bộ phận kỹ thuật thông báo kế hoạch bảo trì định kỳ hệ thống website CMS nhằm cập nhật cấu hình và tối ưu hiệu năng.',
    '<p>Trong thời gian bảo trì, một số thao tác quản trị nội dung có thể bị gián đoạn ngắn.</p><p>Bộ phận kỹ thuật sẽ hoàn tất kiểm tra hệ thống và thông báo ngay khi công tác bảo trì kết thúc.</p>',
    'Thông báo kế hoạch bảo trì định kỳ hệ thống website CMS.',
    '/images/project-office.svg',
    'Announcement',
    2,
    0,
    1,
    '2026-02-25 02:00:00',
    '',
    '',
    '',
    NULL,
    '2026-02-25 02:00:00',
    '2026-02-25 02:00:00'
);
