USE viet_construction_cms;

DELETE FROM Projects
WHERE Slug IN (
    'nha-may-bao-bi-kcn-thuan-an',
    'trung-tam-phan-phoi-da-nang-port',
    'cum-nha-xuong-co-khi-quang-ngai',
    'kho-ngoai-quan-kcn-lien-chieu',
    'toa-nha-dieu-hanh-khu-cong-nghiep-hai-lang',
    'benh-vien-da-khoa-phu-xuan-giai-doan-2',
    'truong-pho-thong-lien-cap-song-han',
    'khu-nha-o-chuyen-gia-green-gate',
    'trung-tam-thuong-mai-hanh-chinh-tam-ky',
    'ha-tang-ky-thuat-khu-do-thi-nam-tuy-hoa',
    'nha-may-go-noi-that-binh-phuoc',
    'khu-logistics-cang-chan-may',
    'tram-xu-ly-nuoc-thai-kcn-dien-nam',
    'toa-nha-van-phong-tech-hub-da-nang',
    'kho-lanh-thuy-san-bac-lieu',
    'nha-may-duoc-pham-phu-yen',
    'trung-tam-du-lieu-mien-trung',
    'khu-ky-tuc-xa-cong-nhan-kcn-hoa-cam',
    'nha-ga-van-hanh-bus-bien-hoa',
    'cong-vien-noi-bo-va-ha-tang-canh-quan-riverside'
);

INSERT INTO Projects (
    Title,
    Slug,
    Summary,
    BodyHtml,
    ClientName,
    Location,
    Scale,
    FeaturedImageUrl,
    IsFeatured,
    IsPublished,
    Status,
    DisplayOrder,
    StartedOn,
    CompletedOn,
    CreatedAtUtc,
    UpdatedAtUtc
) VALUES
(
    'Nhà máy bao bì KCN Thuận An',
    'nha-may-bao-bi-kcn-thuan-an',
    'Tổng thầu thi công kết cấu, hoàn thiện và hạ tầng phụ trợ cho nhà máy bao bì công nghiệp tại Bình Dương.',
    '<p>Dự án bao gồm khu nhà xưởng chính, khối phụ trợ và các hạng mục hạ tầng kỹ thuật nội bộ.</p><p>Ban điều hành tập trung kiểm soát tiến độ kết cấu thép và phối hợp đồng bộ với hệ thống cơ điện.</p>',
    'Công ty Cổ phần Bao bì Đông Nam',
    'Bình Dương',
    '18.000 m2 sàn',
    '/images/project-office.svg',
    1,
    1,
    'Ongoing',
    5,
    '2026-01-08 02:00:00',
    NULL,
    '2026-01-08 02:00:00',
    '2026-01-08 02:00:00'
),
(
    'Trung tâm phân phối Da Nang Port',
    'trung-tam-phan-phoi-da-nang-port',
    'Thi công kho trung chuyển, bãi container và hạ tầng giao thông nội bộ cho trung tâm phân phối gần cảng.',
    '<p>Công trình được tổ chức thành nhiều phân khu kho và bãi logistics để phục vụ vận hành theo từng giai đoạn.</p><p>Doanh nghiệp phụ trách thi công hạ tầng, nhà kho và khu điều phối phương tiện.</p>',
    'Công ty TNHH Da Nang Port Logistics',
    'Đà Nẵng',
    '9,6 ha',
    '/images/project-bridge.svg',
    1,
    1,
    'Ongoing',
    6,
    '2026-01-15 02:00:00',
    NULL,
    '2026-01-15 02:00:00',
    '2026-01-15 02:00:00'
),
(
    'Cụm nhà xưởng cơ khí Quảng Ngãi',
    'cum-nha-xuong-co-khi-quang-ngai',
    'Triển khai kết cấu và hoàn thiện cho cụm ba nhà xưởng cơ khí chế tạo tại khu công nghiệp phía Nam Quảng Ngãi.',
    '<p>Dự án bao gồm nhiều block xưởng sản xuất và khu kỹ thuật phụ trợ.</p><p>Việt Thành Công chịu trách nhiệm thi công nền móng, kết cấu chính và các hạng mục phụ trợ đi kèm.</p>',
    'Công ty Cơ khí Đại Nam Phát',
    'Quảng Ngãi',
    '22.500 m2 sàn',
    '/images/project-residential.svg',
    0,
    1,
    'Ongoing',
    7,
    '2026-02-01 02:00:00',
    NULL,
    '2026-02-01 02:00:00',
    '2026-02-01 02:00:00'
),
(
    'Kho ngoại quan KCN Liên Chiểu',
    'kho-ngoai-quan-kcn-lien-chieu',
    'Dự án kho ngoại quan phục vụ lưu trữ và trung chuyển hàng hóa với yêu cầu tiến độ cao.',
    '<p>Công trình tập trung vào hệ thống nền kho, nhà kho chính và khu phụ trợ quản lý vận hành.</p><p>Tiến độ được chia thành các mốc nhỏ để bảo đảm sẵn sàng khai thác từng phần.</p>',
    'Công ty Cổ phần Liên Chiểu Storage',
    'Đà Nẵng',
    '14.200 m2 sàn',
    '/images/project-office.svg',
    0,
    1,
    'Ongoing',
    8,
    '2026-02-10 02:00:00',
    NULL,
    '2026-02-10 02:00:00',
    '2026-02-10 02:00:00'
),
(
    'Tòa nhà điều hành Khu công nghiệp Hải Lăng',
    'toa-nha-dieu-hanh-khu-cong-nghiep-hai-lang',
    'Thi công tòa nhà điều hành kết hợp không gian làm việc và trung tâm giám sát kỹ thuật.',
    '<p>Dự án gồm khối văn phòng nhiều tầng, khu tiếp đón và hệ thống kỹ thuật đồng bộ.</p><p>Hồ sơ chất lượng được kiểm soát theo từng tầng và từng gói thầu chuyên môn.</p>',
    'Ban Quản lý KCN Hải Lăng',
    'Quảng Trị',
    '7.800 m2 sàn',
    '/images/project-office.svg',
    0,
    1,
    'Ongoing',
    9,
    '2026-02-18 02:00:00',
    NULL,
    '2026-02-18 02:00:00',
    '2026-02-18 02:00:00'
),
(
    'Bệnh viện đa khoa Phú Xuân giai đoạn 2',
    'benh-vien-da-khoa-phu-xuan-giai-doan-2',
    'Mở rộng khối khám chữa bệnh, khu kỹ thuật và hệ thống hạ tầng phụ trợ cho bệnh viện đa khoa địa phương.',
    '<p>Phạm vi dự án gồm khối nhà điều trị, khu xét nghiệm và các hạng mục hạ tầng kết nối.</p><p>Công tác thi công được tổ chức nhằm hạn chế ảnh hưởng đến hoạt động vận hành hiện hữu của bệnh viện.</p>',
    'Công ty Cổ phần Y tế Phú Xuân',
    'Huế',
    '11.400 m2 sàn',
    '/images/project-residential.svg',
    0,
    1,
    'Ongoing',
    10,
    '2026-03-01 02:00:00',
    NULL,
    '2026-03-01 02:00:00',
    '2026-03-01 02:00:00'
),
(
    'Trường phổ thông liên cấp Sông Hàn',
    'truong-pho-thong-lien-cap-song-han',
    'Thi công khối lớp học, nhà đa năng và sân trường cho dự án trường học liên cấp mới.',
    '<p>Dự án ưu tiên tiến độ bàn giao theo năm học và yêu cầu an toàn lao động nghiêm ngặt.</p><p>Đội ngũ dự án đồng thời triển khai hồ sơ hoàn công và các gói hoàn thiện nội thất cơ bản.</p>',
    'Tổ chức Giáo dục Sông Hàn',
    'Đà Nẵng',
    '12.600 m2 sàn',
    '/images/project-residential.svg',
    0,
    1,
    'Ongoing',
    11,
    '2026-03-06 02:00:00',
    NULL,
    '2026-03-06 02:00:00',
    '2026-03-06 02:00:00'
),
(
    'Khu nhà ở chuyên gia Green Gate',
    'khu-nha-o-chuyen-gia-green-gate',
    'Phát triển cụm nhà ở chuyên gia, tiện ích nội khu và hạ tầng cảnh quan đồng bộ.',
    '<p>Dự án hướng tới nhóm chuyên gia làm việc tại khu công nghiệp lân cận với tiêu chuẩn hoàn thiện khá cao.</p><p>Doanh nghiệp thi công các block nhà ở thấp tầng cùng hệ thống giao thông và cảnh quan nội khu.</p>',
    'Green Gate Development',
    'Long An',
    '5,2 ha',
    '/images/project-office.svg',
    0,
    1,
    'Ongoing',
    12,
    '2026-03-12 02:00:00',
    NULL,
    '2026-03-12 02:00:00',
    '2026-03-12 02:00:00'
),
(
    'Trung tâm thương mại hành chính Tam Kỳ',
    'trung-tam-thuong-mai-hanh-chinh-tam-ky',
    'Tổng thầu thi công phần thân, hoàn thiện và hạ tầng kết nối cho công trình hỗn hợp thương mại và hành chính.',
    '<p>Khối công trình được thiết kế theo tổ hợp đa chức năng với yêu cầu kiểm soát chặt chẽ về tiến độ hoàn thiện.</p><p>Ban điều hành đang triển khai song song nhiều gói thầu để rút ngắn thời gian bàn giao.</p>',
    'Công ty Cổ phần Đầu tư Tam Kỳ Center',
    'Quảng Nam',
    '15.800 m2 sàn',
    '/images/project-bridge.svg',
    0,
    1,
    'Ongoing',
    13,
    '2026-03-18 02:00:00',
    NULL,
    '2026-03-18 02:00:00',
    '2026-03-18 02:00:00'
),
(
    'Hạ tầng kỹ thuật Khu đô thị Nam Tuy Hòa',
    'ha-tang-ky-thuat-khu-do-thi-nam-tuy-hoa',
    'Thi công giao thông, thoát nước, cấp điện và cảnh quan cho khu đô thị mới phía Nam Tuy Hòa.',
    '<p>Hạng mục hạ tầng kỹ thuật được chia thành nhiều tuyến để thi công cuốn chiếu.</p><p>Doanh nghiệp ưu tiên hoàn tất các tuyến chính để chủ đầu tư sớm khai thác từng phân khu.</p>',
    'Công ty Cổ phần Phát triển Nam Tuy Hòa',
    'Phú Yên',
    '16,4 ha',
    '/images/project-bridge.svg',
    0,
    1,
    'Ongoing',
    14,
    '2026-03-20 02:00:00',
    NULL,
    '2026-03-20 02:00:00',
    '2026-03-20 02:00:00'
),
(
    'Nhà máy gỗ nội thất Bình Phước',
    'nha-may-go-noi-that-binh-phuoc',
    'Hoàn thành thi công nhà máy chế biến gỗ nội thất và khu văn phòng phụ trợ tại Bình Phước.',
    '<p>Dự án đã bàn giao đúng tiến độ với đầy đủ hồ sơ nghiệm thu và hướng dẫn vận hành ban đầu.</p><p>Các hạng mục kết cấu, nền xưởng và phụ trợ được hoàn tất đồng bộ theo yêu cầu khai thác của chủ đầu tư.</p>',
    'Công ty TNHH Woodstyle Việt Nam',
    'Bình Phước',
    '19.300 m2 sàn',
    '/images/project-office.svg',
    1,
    1,
    'Completed',
    15,
    '2025-02-05 02:00:00',
    '2025-12-18 02:00:00',
    '2025-02-05 02:00:00',
    '2025-12-18 02:00:00'
),
(
    'Khu logistics cảng Chân Mây',
    'khu-logistics-cang-chan-may',
    'Bàn giao khu logistics, kho trung chuyển và hạ tầng giao thông kết nối khu vực cảng Chân Mây.',
    '<p>Công trình đã được nghiệm thu và đưa vào khai thác theo từng giai đoạn.</p><p>Doanh nghiệp hoàn tất các gói hạ tầng, kho và khu kỹ thuật phục vụ vận hành logistics.</p>',
    'Chân Mây Logistics JSC',
    'Huế',
    '11,8 ha',
    '/images/project-bridge.svg',
    1,
    1,
    'Completed',
    16,
    '2024-11-01 02:00:00',
    '2025-10-28 02:00:00',
    '2024-11-01 02:00:00',
    '2025-10-28 02:00:00'
),
(
    'Trạm xử lý nước thải KCN Điện Nam',
    'tram-xu-ly-nuoc-thai-kcn-dien-nam',
    'Hoàn thành công trình trạm xử lý nước thải và hệ thống phụ trợ cho khu công nghiệp Điện Nam.',
    '<p>Phạm vi dự án gồm bể xử lý, nhà điều hành và các hạng mục hạ tầng kỹ thuật hỗ trợ vận hành.</p><p>Công trình được bàn giao sau khi hoàn tất chạy thử và nghiệm thu kỹ thuật.</p>',
    'Công ty Hạ tầng Điện Nam',
    'Quảng Nam',
    '4.500 m2 xây dựng',
    '/images/project-residential.svg',
    0,
    1,
    'Completed',
    17,
    '2024-08-14 02:00:00',
    '2025-07-30 02:00:00',
    '2024-08-14 02:00:00',
    '2025-07-30 02:00:00'
),
(
    'Tòa nhà văn phòng Tech Hub Đà Nẵng',
    'toa-nha-van-phong-tech-hub-da-nang',
    'Hoàn thành công trình văn phòng công nghệ với không gian làm việc linh hoạt và hệ thống kỹ thuật hiện đại.',
    '<p>Dự án tập trung vào chất lượng hoàn thiện, hệ thống cơ điện và tiêu chuẩn vận hành văn phòng hiện đại.</p><p>Công trình đã được bàn giao và đưa vào sử dụng ổn định.</p>',
    'Tech Hub Development',
    'Đà Nẵng',
    '9.200 m2 sàn',
    '/images/project-office.svg',
    0,
    1,
    'Completed',
    18,
    '2024-06-10 02:00:00',
    '2025-05-22 02:00:00',
    '2024-06-10 02:00:00',
    '2025-05-22 02:00:00'
),
(
    'Kho lạnh thủy sản Bạc Liêu',
    'kho-lanh-thuy-san-bac-lieu',
    'Thi công hoàn chỉnh khu kho lạnh, nhà điều hành và hạ tầng kỹ thuật phục vụ chuỗi thủy sản xuất khẩu.',
    '<p>Công trình đáp ứng yêu cầu tiến độ gấp để phục vụ mùa vụ và kế hoạch khai thác của chủ đầu tư.</p><p>Doanh nghiệp đã hoàn thiện hồ sơ bàn giao và phối hợp chạy thử các hạng mục kỹ thuật liên quan.</p>',
    'Công ty Thủy sản Miền Nam',
    'Bạc Liêu',
    '13.700 m2 sàn',
    '/images/project-bridge.svg',
    0,
    1,
    'Completed',
    19,
    '2024-05-20 02:00:00',
    '2025-04-10 02:00:00',
    '2024-05-20 02:00:00',
    '2025-04-10 02:00:00'
),
(
    'Nhà máy dược phẩm Phú Yên',
    'nha-may-duoc-pham-phu-yen',
    'Bàn giao nhà máy dược phẩm với các khu vực sản xuất, kho bảo quản và hệ thống kỹ thuật chuyên dụng.',
    '<p>Dự án yêu cầu kiểm soát chặt chẽ về chất lượng hoàn thiện và quy trình phối hợp kỹ thuật.</p><p>Công trình đã được nghiệm thu và bàn giao đúng kế hoạch đã thống nhất với chủ đầu tư.</p>',
    'Phú Yên Pharma',
    'Phú Yên',
    '10.900 m2 sàn',
    '/images/project-residential.svg',
    0,
    1,
    'Completed',
    20,
    '2024-04-12 02:00:00',
    '2025-03-28 02:00:00',
    '2024-04-12 02:00:00',
    '2025-03-28 02:00:00'
),
(
    'Trung tâm dữ liệu miền Trung',
    'trung-tam-du-lieu-mien-trung',
    'Hoàn thành phần xây dựng và hạ tầng kỹ thuật cho trung tâm dữ liệu quy mô trung bình tại miền Trung.',
    '<p>Dự án chú trọng các tiêu chuẩn kỹ thuật, độ ổn định hạ tầng và phối hợp chặt với hệ thống cơ điện.</p><p>Hồ sơ hoàn công và kiểm tra chất lượng được hoàn tất theo đúng quy trình nội bộ.</p>',
    'Central Data Infrastructure',
    'Đà Nẵng',
    '6.800 m2 sàn',
    '/images/project-office.svg',
    0,
    1,
    'Completed',
    21,
    '2024-03-01 02:00:00',
    '2025-02-14 02:00:00',
    '2024-03-01 02:00:00',
    '2025-02-14 02:00:00'
),
(
    'Khu ký túc xá công nhân KCN Hòa Cầm',
    'khu-ky-tuc-xa-cong-nhan-kcn-hoa-cam',
    'Thi công và bàn giao khu ký túc xá công nhân, tiện ích nội khu và hệ thống hạ tầng phụ trợ.',
    '<p>Dự án hướng tới nhu cầu lưu trú tập trung cho lực lượng lao động tại khu công nghiệp.</p><p>Công trình đã hoàn thiện đồng bộ phần nhà ở, cảnh quan và hạ tầng dịch vụ nội bộ.</p>',
    'Công ty Hạ tầng Hòa Cầm',
    'Đà Nẵng',
    '8.900 m2 sàn',
    '/images/project-residential.svg',
    0,
    1,
    'Completed',
    22,
    '2024-01-16 02:00:00',
    '2024-12-20 02:00:00',
    '2024-01-16 02:00:00',
    '2024-12-20 02:00:00'
),
(
    'Nhà ga vận hành bus Biên Hòa',
    'nha-ga-van-hanh-bus-bien-hoa',
    'Hoàn thành nhà ga điều hành, khu bảo trì và các hạng mục kỹ thuật phục vụ vận hành tuyến bus đô thị.',
    '<p>Doanh nghiệp triển khai công trình theo tiến độ ngắn với yêu cầu phối hợp nhiều đơn vị kỹ thuật.</p><p>Toàn bộ khối nhà điều hành và hạ tầng phụ trợ đã được bàn giao phục vụ khai thác.</p>',
    'Biên Hòa Transit',
    'Đồng Nai',
    '5.600 m2 sàn',
    '/images/project-bridge.svg',
    0,
    1,
    'Completed',
    23,
    '2023-11-20 02:00:00',
    '2024-10-30 02:00:00',
    '2023-11-20 02:00:00',
    '2024-10-30 02:00:00'
),
(
    'Công viên nội bộ và hạ tầng cảnh quan Riverside',
    'cong-vien-noi-bo-va-ha-tang-canh-quan-riverside',
    'Bàn giao công viên nội bộ, lối dạo, cảnh quan và hệ thống chiếu sáng cho khu đô thị ven sông.',
    '<p>Dự án gồm nhiều hạng mục cảnh quan, đường dạo, quảng trường nhỏ và hệ thống tưới tự động.</p><p>Việt Thành Công hoàn thiện công trình theo đúng thiết kế và yêu cầu vận hành của chủ đầu tư.</p>',
    'Riverside Urban Development',
    'Quảng Nam',
    '7,1 ha',
    '/images/project-office.svg',
    0,
    1,
    'Completed',
    24,
    '2023-09-05 02:00:00',
    '2024-08-12 02:00:00',
    '2023-09-05 02:00:00',
    '2024-08-12 02:00:00'
);
